name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Portal UAD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Set Current Date and Time As Env Variable
      - name: Set current date and time as env variable
        run: echo "date_time_now=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print \\\\\\\\$2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:assembleDebug

      # Create Bundle AAB Release
      # Noted for main module build [main_project_module]:bundleRelease
      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Get commit messages
      - name: Get commit messages
        id: commit_messages
        run: |
          echo "::set-output name=messages::$(git log --pretty=format:"%s" -10)"

      - name: Get VirusTotal upload URL
        id: get_upload_url
        run: |
          response=$(curl --request GET 'https://www.virustotal.com/api/v3/files/upload_url' --header 'x-apikey: ${{ secrets.VT_API_KEY }}')
          upload_url=$(echo $response | jq -r .data)
          echo "::set-output name=upload_url::$upload_url"

      - name: Upload APK to VirusTotal and get report URL
        id: virustotal
        run: |
          apk_path=./${{ env.main_project_module }}/build/outputs/apk/debug/app-debug.apk
          response=$(curl --request POST "${{ steps.get_upload_url.outputs.upload_url }}" \
          --header 'x-apikey: ${{ secrets.VT_API_KEY }}' \
          --form 'file=@'$apk_path)
          echo "Response: $response"
          resource=$(echo $response | jq -r .data.id)
          echo "::set-output name=report_url::https://www.virustotal.com/gui/file/$resource/detection"


      # Create a GitHub release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.date_time_now }}
          release_name: Release ${{ env.date_time_now }}
          body: |
            Release of ${{ env.date_time_now }}
            Commit Changes:
            ${{ steps.commit_messages.outputs.messages }}
            VirusTotal Report:
            ${{ steps.virustotal.outputs.report_url }}
          draft: false
          prerelease: true

      # Upload APK Debug to GitHub release
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.main_project_module }}/build/outputs/apk/debug/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
